
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "feature", "feature*" ]
  pull_request:
    branches: [ "main", "feature", "feature*" ]

env:
  WEBMEMBERSHIP: "1.0"
  PRODUCT: "webmembership"

jobs:
  build_jar:
    #runs-on: ubuntu-latest
    runs-on: Windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'microsoft'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true

    - name: List files in the Directory - target
      run: dir target

    - name: Copy JAR to the Staging Directory
      run: New-Item -type Directory -name staging; Copy-Item -Path "target\*.jar" -Destination "staging"

    - name: Upload JAR Artifacts 
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: staging
        retention-days: 1
        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  build_exe:
    needs: build_jar
    runs-on: Windows
    
    steps:
    - uses: actions/checkout@v4

    - name: Set ENV Variables
      run: |
        Write-Output "RELEASE=${env:WEBMEMBERSHIP}_RELEASE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "BUILD_DIR=tmp/web_build/Java11Upgrade/${env:PRODUCT}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Set ENV Variables
      run: |
        Write-Output "BIN_FILE_TAR_ZIP=${env:PRODUCT}_v${env:RELEASE}.tar" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "TARGET_DIR=${env:PRODUCT}_v${env:RELEASE}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: Print ENV Variables
      run: |
        echo "WEBMEMBERSHIP = $env:WEBMEMBERSHIP"
        echo "PRODUCT = $env:PRODUCT"
        echo "RELEASE = $env:RELEASE"
        echo "BUILD_DIR = $env:BUILD_DIR"
        echo "TARGET_DIR = $env:TARGET_DIR"
        echo "BIN_FILE_TAR_ZIP = $env:BIN_FILE_TAR_ZIP"
     
    - name: Download Artifacts 
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: staging

    - name: List Artifacts
      run: dir staging

    - name: Create Target Directory - "$env:BUILD_DIR/$env:TARGET_DIR"
      run: |
        If (!(Test-Path "$env:BUILD_DIR/$env:TARGET_DIR")) {
          New-Item -type Directory -name "$env:BUILD_DIR/$env:TARGET_DIR"
        }

    - name: Copy JAR to the Target Directory - "$env:BUILD_DIR/$env:TARGET_DIR"
      run: Copy-Item -Path "staging/*.jar" -Destination "$env:BUILD_DIR/$env:TARGET_DIR"

    - name: Create .sh Files
      run: |
        cd $env:BUILD_DIR/$env:TARGET_DIR
        New-Item -type File -name "sample.sh"
        New-Item -type File -name "new.sh"
        cd ..

    - name: Create JAR Files
      run: |
        Copy-Item -Path "staging/*.jar" -Destination "$env:BUILD_DIR/$env:TARGET_DIR/test.jar"
        Copy-Item -Path "staging/*.jar" -Destination "$env:BUILD_DIR/$env:TARGET_DIR/hello.jar"

    # - name: Copy Build Scripts to the Target Directory - "$env:BUILD_DIR/$env:TARGET_DIR"
    #   run: |
    #     Copy-Item -Path "API/build_script/install-$env:PRODUCT.sh" -Destination "$env:BUILD_DIR/$env:TARGET_DIR"
    #     Copy-Item -Path "API/build_script/append_properties.sh" -Destination "$env:BUILD_DIR/$env:TARGET_DIR"
    #     Copy-Item -Path "API/build_script/jsonmerger.jar" -Destination "$env:BUILD_DIR/$env:TARGET_DIR"

    # - name: List Artifacts
    #   run: dir "$env:BUILD_DIR/$env:TARGET_DIR"

    # - name: Copy version file to the Target Directory - "$env:BUILD_DIR/$env:TARGET_DIR"
    #   run: |
    #     Copy-Item -Path "API/Server/bin/version.txt" -Destination "$env:BUILD_DIR/$env:TARGET_DIR" -Force -Recurse
    #     Copy-Item -Path "API/Server/bin/${env:PRODUCT}_env" -Destination "$env:BUILD_DIR/$env:TARGET_DIR" -Force -Recurse

    - name: Set All File Permissions in the Target Directory - [chmod 644 $targetdir/*]
      shell: powershell
      run:  | 
        $files = Get-ChildItem -Path "$env:BUILD_DIR/$env:TARGET_DIR" -Filter "*"
        foreach ($file in $files) {
          $acl = Get-Acl $file.FullName
          $rule = New-Object System.Security.AccessControl.FileSystemAccessRule("Users", "ReadAndExecute", "Allow")
          $acl.SetAccessRule($rule)
          Set-Acl -Path $file.FullName -AclObject $acl
        }

    - name: Set .sh File Permissions in the Target Directory - [chmod 755 $targetdir/*.sh]
      shell: powershell
      run:  | 
        $files = Get-ChildItem -Path "$env:BUILD_DIR/$env:TARGET_DIR" -Filter "*.sh"
        foreach ($file in $files) {
          $acl = Get-Acl -Path $file.FullName
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("Everyone", "ReadAndExecute", "Allow")
          $ownerRule = New-Object System.Security.AccessControl.FileSystemAccessRule("BUILTIN\Administrators", "FullControl", "Allow")
          $acl.SetAccessRule($accessRule)
          $acl.SetAccessRule($ownerRule)
          Set-Acl -Path $file.FullName -AclObject $acl
        }

    - name: Set .jar File Permissions in the Target Directory - [chmod 755 $targetdir/*.jar]
      shell: powershell
      run:  | 
        $files = Get-ChildItem -Path "$env:BUILD_DIR/$env:TARGET_DIR" -Filter "*.jar"
        foreach ($file in $files) {
          $acl = Get-Acl -Path $file.FullName
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("Everyone", "ReadAndExecute", "Allow")
          $ownerRule = New-Object System.Security.AccessControl.FileSystemAccessRule("BUILTIN\Administrators", "FullControl", "Allow")
          $acl.SetAccessRule($accessRule)
          $acl.SetAccessRule($ownerRule)
          Set-Acl -Path $file.FullName -AclObject $acl
        }

    - name: List .sh Files
      run: |
        $files = Get-ChildItem -Path "$env:BUILD_DIR/$env:TARGET_DIR" -Filter "*.sh"
        foreach ($file in $files) {
          Write-Output "File: $($file.FullName)"
          Get-Acl -Path $file.FullName | Format-List
        }

    - name: List .jar Files
      run: |
        $files = Get-ChildItem -Path "$env:BUILD_DIR/$env:TARGET_DIR" -Filter "*.jar"
        foreach ($file in $files) {
          Write-Output "File: $($file.FullName)"
          Get-Acl -Path $file.FullName | Format-List
        }

    - name: Compress action step
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./"$BUILD_DIR"
        files: |
          ./"$TARGET_DIR"
        outPath: $BIN_FILE_TAR_ZIP

    - name: List Artifacts
      run: dir "$env:BUILD_DIR/$env:BIN_FILE_TAR_ZIP"
